name: first
on: push
jobs:
  job1:
    name: First job
    runs-on: ubuntu-22.04
    steps:
      - name: Step one
        uses: actions/checkout@v4.1.2
      - name: Step two
        run: env | sort
  job2:
    name: Second job
    runs-on: ubuntu-20.04
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: echo Hi
  job3:
    name: Third job
    runs-on: ubuntu-22.04
    needs: [ job1, job2 ]
    steps:
      - name: Step one
        run: echo Hi
        
